environment:
  matrix:
    - QTDIR: C:\Qt\5.6\mingw49_32
      MINGW: C:\Qt\Tools\mingw49_32
      COMPILER_NAME: mingw49_32
    - QTDIR: C:\Qt\5.9.1\mingw53_32
      MINGW: C:\Qt\Tools\mingw53_32
      COMPILER_NAME: mingw53_32
    - QTDIR: C:\Qt\5.7\msvc2015
      COMPILER_NAME: msvc2015
    - QTDIR: C:\Qt\5.7\msvc2015_64
      COMPILER_NAME: msvc2015_64
    - QTDIR: C:\Qt\5.9.1\msvc2017_64
      COMPILER_NAME: msvc2017_64

configuration:
  - debug
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - pushd %QTDIR% && dir && popd
  - '%QTDIR%\bin\qtenv2.bat'
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2017=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

# Run qmake
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake CONFIG+=%CONFIGURATION% geometrize-lib-example.pro

# Build the project
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - '%make%'
  - move %CONFIGURATION%\geometrize_lib_example.exe geometrize_lib_example_%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_BUILD_ID%_%COMPILER_NAME%_%CONFIGURATION%.exe

# Gather artifacts
artifacts:
  - path: '**\*.exe'
    name: geometrize_lib_example
    type: File

# Deploy artifacts
deploy:
  provider: S3
  access_key_id: $(AWS_ACCESS_KEY_ID)
  secret_access_key: $(AWS_SECRET_ACCESS_KEY)
  bucket: $(AWS_S3_BUCKET_NAME)
  region: us-east-1
  unzip: false
  set_public: true
  folder: windows
  artifact: geometrize_lib_example